name = "CoolTensors"
uuid = "85b16c79-57f6-4a30-832b-f4a8791f4758"
authors = ["Simeon Schaub <simeondavidschaub99@gmail.com> and contributors"]
version = "0.1.0"

[deps]
TensorCore = "62fd8b95-f654-4bbd-a8a5-9c27f68ccd50"

[compat]
TensorCore = "0.1"
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "LinearAlgebra", "Test"]
